/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAlbums {
    }
    interface AppArtists {
    }
    interface AppHome {
        "resizeHorizontal": boolean;
        "resizeVertical": boolean;
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAlbumsElement extends Components.AppAlbums, HTMLStencilElement {
    }
    var HTMLAppAlbumsElement: {
        prototype: HTMLAppAlbumsElement;
        new (): HTMLAppAlbumsElement;
    };
    interface HTMLAppArtistsElement extends Components.AppArtists, HTMLStencilElement {
    }
    var HTMLAppArtistsElement: {
        prototype: HTMLAppArtistsElement;
        new (): HTMLAppArtistsElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-albums": HTMLAppAlbumsElement;
        "app-artists": HTMLAppArtistsElement;
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAlbums {
    }
    interface AppArtists {
    }
    interface AppHome {
        "resizeHorizontal"?: boolean;
        "resizeVertical"?: boolean;
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-albums": AppAlbums;
        "app-artists": AppArtists;
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-albums": LocalJSX.AppAlbums & JSXBase.HTMLAttributes<HTMLAppAlbumsElement>;
            "app-artists": LocalJSX.AppArtists & JSXBase.HTMLAttributes<HTMLAppArtistsElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
